/**
 * WGSL twins of the custom splat shader chunks in `splat-shader.ts`.
 *
 * Why this file exists: on the WebGPU backend PlayCanvas compiles the splat
 * material from its **WGSL** sources. `shader-generator-shader.js` picks WGSL
 * whenever the material carries WGSL sources and `shaderChunks.useWGSL` is true,
 * and `GSplatResourceBase.configureMaterial()` always fills the *wgsl* chunk map
 * on a WebGPU device 閳?so overriding only the GLSL chunks (`shaderChunks.glsl`)
 * silently does nothing there: the engine's stock WGSL splat shader runs instead,
 * which ignores every SplatRoom feature (colour grading, hidden/deleted state,
 * crop box, particle effects, transform palette, selection overlay) and declares a
 * single fragment output, making our two-attachment splat pass an invalid pipeline
 * (Dawn: "Color target has no corresponding fragment stage output", targets[1]).
 * See docs/V3-WebGPU-閻滄壆濮?md.
 *
 * Chunk mapping 閳?the same four chunks the GLSL path overrides:
 *   `vertexShaderWGSL`  閳?`gsplatVS`        (vertex entry, replaces the engine's)
 *   `fragmentShaderWGSL`閳?`gsplatPS`        (fragment entry)
 *   `gsplatCenterWGSL`  閳?`gsplatCenterVS`  (`initCenter` + transform palette)
 *   `gsplatModifyWGSL`  閳?`gsplatModifyVS`  (`modifySplat*` hooks)
 *
 * WGSL dialect notes (these are PlayCanvas processor conventions, not plain WGSL):
 *   - `varying name: type;` declarations are collected into VertexOutput/FragmentInput;
 *     locations are assigned from the *vertex* stage order and matched by name, so the
 *     fragment may declare them in any order but the names/types must match.
 *   - loose `uniform name: type;` declarations from both stages are merged into one
 *     uniform buffer and must be *accessed* as `uniform.name` in the chunk body; the
 *     processor rewrites that into the generated buffer access.
 *   - textures are declared as `var name: texture_2d<f32>;` and read with
 *     `textureLoad(name, splat.uv, 0)` (no sampler needed).
 *   - the `FragmentOutput` struct is generated by scanning the fragment source for
 *     `output.colorN = ...` assignments, so writing `output.color1` here is what
 *     makes the two-attachment (cameraColor + workColor) splat pass valid.
 *   - struct pointer parameters auto-dereference on member access (`corner.offset`).
 */

// Vertex stage: mirrors `vertexShader` in splat-shader.ts. Reads the per-splat edit
// state, applies the SplatRoom particle effects to the centre, then the engine's
// centre/corner projection, and finally packs the corner uv, the selection flags and
// the crop-box ellipse data into varyings for the fragment stage.
const vertexShaderWGSL = /* wgsl */`
#include "gsplatCommonVS"

// per-splat edit state (R8): bit0 selected, bit1 locked, bit2 deleted
var splatState: texture_2d<f32>;

uniform selectedClr: vec4f;
uniform lockedClr: vec4f;

uniform clrOffset: vec3f;
uniform clrScale: vec4f;

varying texCoord_flags: vec4f;              // xy: corner uv, z: selected, w: locked
varying color: vec4f;
varying vDeleted: f32;                      // 1.0 if deleted-but-shown, 0.0 otherwise

// oriented crop-box clipping (SplatRoom)
uniform uCropBoxEnabled: f32;
uniform uCropBoxPreview: f32;
uniform uCropBoxSoftEdge: f32;
uniform uViewToBoxLocal: mat4x4f;
varying vViewCenter: vec3f;
varying vScreenOffset: vec2f;
varying vDepthRadius: f32;
varying vEllipE00: f32;
varying vEllipE01: f32;
varying vEllipE02: f32;
varying vEllipE11: f32;
varying vEllipE12: f32;
varying vEllipE22: f32;

uniform showDeleted: f32;

// particle scatter (SplatRoom effect): interpolates each gaussian between its real
// position and a random particle position inside the bounding sphere.
// uScatterProgress: 0 = full model, 1 = fully scattered
#ifndef PICK_PASS
    uniform uScatterProgress: f32;
    uniform uScatterRadius: f32;
    uniform uScatterCenter: vec3f;

    // effect mode: 0 = plain scatter; 1 = ripple intro (wave sweeps the model into
    // place); 2 = drift outro (model bursts into sparks that fall away)
    uniform uEffectMode: i32;
    uniform uEffectTime: f32;               // 0..1 progress of the layer effect
    uniform uEffectColor: vec3f;            // highlight colour of the wave / sparks
    uniform uEffectFade: f32;               // overall opacity 0..1 (intro/outro fade)
#endif

#if PICK_PASS
    uniform pickOp: u32;                    // 0: add, 1: remove, 2: set
    uniform pickMode: i32;                  // 0: pick id, 1: depth estimation
#endif

uniform saturation: f32;

const discardVec: vec4f = vec4f(0.0, 0.0, 2.0, 1.0);

fn applySaturationToColor(c: vec3f) -> vec3f {
    let grey: vec3f = vec3f(dot(c, vec3f(0.299, 0.587, 0.114)));
    return grey + (c - grey) * uniform.saturation;
}

// per-splat hashed random numbers, shared with the modify hook
fn splatSeed() -> f32 {
    return f32(splat.uv.x) * 0.61803398875 + f32(splat.uv.y) * 0.38196601125;
}

@vertex
fn vertexMain(input: VertexInput) -> VertexOutput {
    var output: VertexOutput;

    // read gaussian details
    var source: SplatSource;
    if (!initSource(&source)) {
        output.position = discardVec;
        return output;
    }

    // per-gaussian edit state
    let vertexState: u32 = u32(textureLoad(splatState, splat.uv, 0).r * 255.0 + 0.5) & 7u;

    #if PICK_PASS
        if (uniform.pickOp == 0u) {
            // add: skip locked and already-selected; skip deleted unless showDeleted
            if ((vertexState & 2u) != 0u || (vertexState & 1u) != 0u) {
                output.position = discardVec;
                return output;
            }
            if ((vertexState & 4u) != 0u && uniform.showDeleted < 0.5) {
                output.position = discardVec;
                return output;
            }
        } else if (uniform.pickOp == 1u) {
            // remove: pick selected splats (skip locked and unselected)
            if ((vertexState & 2u) != 0u || (vertexState & 1u) == 0u) {
                output.position = discardVec;
                return output;
            }
        } else {
            // set: skip locked; skip deleted unless showDeleted
            if ((vertexState & 2u) != 0u) {
                output.position = discardVec;
                return output;
            }
            if ((vertexState & 4u) != 0u && uniform.showDeleted < 0.5) {
                output.position = discardVec;
                return output;
            }
        }
    #else
        // skip deleted splats (unless showDeleted is enabled)
        output.vDeleted = 0.0;
        if ((vertexState & 4u) != 0u) {
            if (uniform.showDeleted < 0.5) {
                output.position = discardVec;
                return output;
            }
            output.vDeleted = 1.0;
        }
    #endif

    // get center
    var modelCenter: vec3f = getCenter();

    // ===== particle effects (SplatRoom): position transform =====
    // PICK_PASS keeps the real position so picking still hits the real gaussian.
    #ifndef PICK_PASS
        let seed: f32 = splatSeed();
        let r1: f32 = fract(sin(seed * 12.9898) * 43758.5453);
        let r2: f32 = fract(sin(seed * 78.233) * 12543.123);
        let r3: f32 = fract(sin(seed * 33.912) * 7951.192);
        let scatterDir: vec3f = normalize(vec3f(r1 - 0.5, r2 - 0.5, r3 - 0.5));
        let scatterDist: f32 = uniform.uScatterRadius * (0.3 + r3 * 0.7);
        let scatterPos: vec3f = uniform.uScatterCenter + scatterDir * scatterDist;

        if (uniform.uEffectMode == 1) {
            // ripple intro: the wave front clusters particles into the model
            let waveRadius: f32 = uniform.uEffectTime * uniform.uScatterRadius * 1.6;
            let waveWidth: f32 = uniform.uScatterRadius * 0.12;
            let d: f32 = length(modelCenter - uniform.uScatterCenter);
            if (d < waveRadius) {
                // wave already passed: full model at the real position
            } else if (d < waveRadius + waveWidth) {
                // wave front: particles halfway between scatter and real position
                let bandT: f32 = (d - waveRadius) / max(waveWidth, 1e-5);
                modelCenter = mix(modelCenter, scatterPos, bandT);
            } else {
                // wave not reached yet: still scattered (faded out in the fragment)
                modelCenter = scatterPos;
            }
        } else if (uniform.uEffectMode == 2) {
            // drift outro: burst into particles, then fall with gravity
            let delay: f32 = r3 * 0.15;
            let burstT: f32 = clamp((uniform.uEffectTime - delay) / max(0.2, 1.0 - delay), 0.0, 1.0);
            let burstPos: vec3f = mix(modelCenter, scatterPos, burstT);
            let hdir: vec2f = normalize(vec2f(r1 - 0.5, r2 - 0.5));
            let fall: f32 = burstT * burstT;
            modelCenter = burstPos + vec3f(
                hdir.x * uniform.uScatterRadius * 0.15 * burstT,
                -uniform.uScatterRadius * 1.6 * fall,
                hdir.y * uniform.uScatterRadius * 0.15 * burstT
            );
        } else {
            // plain scatter: 0 = model, 1 = particles
            modelCenter = mix(modelCenter, scatterPos, uniform.uScatterProgress);
        }
    #endif

    var center: SplatCenter;
    center.modelCenterOriginal = modelCenter;
    center.modelCenterModified = modelCenter;
    if (!initCenter(modelCenter, &center)) {
        output.position = discardVec;
        return output;
    }

    var corner: SplatCorner;
    if (!initCorner(&source, &center, &corner)) {
        output.position = discardVec;
        return output;
    }

    output.position = center.proj + vec4f(corner.offset.xyz, 0.0);

    // Safety net for exact axis-aligned ortho views (azim 0/90/180/270 with elev 0):
    // the engine's covariance projection can normalize a degenerate screen-space
    // covariance and produce NaN, which puts the vertex outside clip space and makes
    // the whole model disappear. Fall back to a tiny constant offset. WGSL has no
    // isnan/isinf builtin, so NaN is detected by comparing a value with itself, and
    // infinity by a magnitude test (comparisons need matching operand shapes).
    var safeOffset: vec2f = corner.offset.xy;
    if (any(corner.offset != corner.offset) || any(abs(corner.offset) > vec3f(1e30))) {
        safeOffset = vec2f(source.cornerUV) * 0.02;
        output.position = vec4f(center.proj.xy + safeOffset, center.proj.z, 1.0);
    }

    // crop-box vertex data for per-fragment clipping
    if (uniform.uCropBoxEnabled > 0.5) {
        output.vViewCenter = center.view;
        let clipPos: vec4f = center.proj + vec4f(safeOffset, 0.0, 0.0);

        // reconstruct the fragment's absolute view-space xy (same units as
        // center.view): the clip-space offset scaled by the depth factor / the linear
        // part of the projection. The depth factor is -viewZ for perspective and 1 for
        // orthographic (which has no view-z Jacobian).
        let viewSpaceXY: vec2f = safeOffset *
            select(-center.view.z, 1.0, uniform.uSplatCameraParams.w == 1.0) /
            (clipPos.w * vec2f(uniform.uSplatProj[0][0], uniform.uSplatProj[1][1]));
        output.vScreenOffset = output.vViewCenter.xy + viewSpaceXY;

        let rotH: half3x3 = quatToMat3(half4(getRotation().yzwx));
        let rotMat: mat3x3f = mat3x3f(vec3f(rotH[0]), vec3f(rotH[1]), vec3f(rotH[2]));
        let splatScale: vec3f = getScale();
        let worldMat: mat4x4f = applyPaletteTransform(uniform.matrix_model);
        let axis0: vec3f = splatScale.x * (worldMat * vec4f(rotMat[0], 0.0)).xyz;
        let axis1: vec3f = splatScale.y * (worldMat * vec4f(rotMat[1], 0.0)).xyz;
        let axis2: vec3f = splatScale.z * (worldMat * vec4f(rotMat[2], 0.0)).xyz;
        let viewRot: mat3x3f = transpose(mat3x3f(
            vec3f(uniform.uSplatView[0].xyz),
            vec3f(uniform.uSplatView[1].xyz),
            vec3f(uniform.uSplatView[2].xyz)
        ));
        let viewDir: vec3f = viewRot[2];
        let d0: f32 = dot(axis0, viewDir);
        let d1: f32 = dot(axis1, viewDir);
        let d2: f32 = dot(axis2, viewDir);
        output.vDepthRadius = 3.0 * sqrt(d0 * d0 + d1 * d1 + d2 * d2);

        let viewMat: mat3x3f = mat3x3f(
            vec3f(uniform.uSplatView[0].xyz),
            vec3f(uniform.uSplatView[1].xyz),
            vec3f(uniform.uSplatView[2].xyz)
        );
        let M: mat3x3f = viewMat * rotMat;
        let invA0: f32 = 1.0 / max(splatScale.x * splatScale.x, 1e-8);
        let invA1: f32 = 1.0 / max(splatScale.y * splatScale.y, 1e-8);
        let invA2: f32 = 1.0 / max(splatScale.z * splatScale.z, 1e-8);
        output.vEllipE00 = M[0][0] * M[0][0] * invA0 + M[0][1] * M[0][1] * invA1 + M[0][2] * M[0][2] * invA2;
        output.vEllipE01 = M[0][0] * M[1][0] * invA0 + M[0][1] * M[1][1] * invA1 + M[0][2] * M[1][2] * invA2;
        output.vEllipE02 = M[0][0] * M[2][0] * invA0 + M[0][1] * M[2][1] * invA1 + M[0][2] * M[2][2] * invA2;
        output.vEllipE11 = M[1][0] * M[1][0] * invA0 + M[1][1] * M[1][1] * invA1 + M[1][2] * M[1][2] * invA2;
        output.vEllipE12 = M[1][0] * M[2][0] * invA0 + M[1][1] * M[2][1] * invA1 + M[1][2] * M[2][2] * invA2;
        output.vEllipE22 = M[2][0] * M[2][0] * invA0 + M[2][1] * M[2][1] * invA1 + M[2][2] * M[2][2] * invA2;
    } else {
        output.vViewCenter = vec3f(0.0);
        output.vScreenOffset = vec2f(0.0);
        output.vDepthRadius = 0.0;
        output.vEllipE00 = 0.0;
        output.vEllipE01 = 0.0;
        output.vEllipE02 = 0.0;
        output.vEllipE11 = 0.0;
        output.vEllipE12 = 0.0;
        output.vEllipE22 = 0.0;
    }

    // store texture coord and selection flags
    output.texCoord_flags = vec4f(
        f32(corner.uv.x),
        f32(corner.uv.y),
        select(0.0, 1.0, (vertexState & 1u) != 0u),
        select(0.0, 1.0, (vertexState & 2u) != 0u)
    );

    #if PICK_PASS
        if (uniform.pickMode == 1) {
            // depth estimation mode: normalized linear depth (blended additively)
            let linearDepth: f32 = -center.view.z;
            let normalizedDepth: f32 = (linearDepth - uniform.uSplatCameraParams.z) / (uniform.uSplatCameraParams.y - uniform.uSplatCameraParams.z);
            let srcClr: vec4f = getColor();
            output.color = vec4f(normalizedDepth, 0.0, 0.0, 1.0) * srcClr.a;
        } else {
            // pick id
            let bits: vec4u = (vec4u(splat.index) >> vec4u(0u, 8u, 16u, 24u)) & vec4u(255u);
            output.color = vec4f(bits) / 255.0;
        }
    #else
        // handle splat color
        var clr: vec4f = getColor();

        // evaluate spherical harmonics
        #if SH_BANDS > 0
            let modelView3x3: mat3x3f = mat3x3f(center.modelView[0].xyz, center.modelView[1].xyz, center.modelView[2].xyz);
            let dir: vec3f = normalize(center.view * modelView3x3);

            var sh: array<half3, SH_COEFFS>;
            var shScale: f32;
            readSHData(&sh, &shScale);
            clr = vec4f(clr.xyz + vec3f(evalSH(&sh, dir)) * shScale, clr.w);
        #endif

        // apply tint/brightness
        clr = clr * uniform.clrScale + vec4f(uniform.clrOffset, 0.0);

        // ===== effect colour / opacity (SplatRoom) =====
        if (uniform.uEffectMode == 1) {
            // ripple intro: wave front glows slightly, unreached particles fade out
            let waveRadius: f32 = uniform.uEffectTime * uniform.uScatterRadius * 1.6;
            let waveWidth: f32 = uniform.uScatterRadius * 0.12;
            let d: f32 = length(modelCenter - uniform.uScatterCenter);
            if (d < waveRadius) {
                // already revealed: normal colour
            } else if (d < waveRadius + waveWidth) {
                let bandT: f32 = (d - waveRadius) / max(waveWidth, 1e-5);
                let glow: f32 = 1.0 - bandT;
                clr = vec4f(mix(clr.xyz, uniform.uEffectColor, 0.25 * glow), clr.w);
                clr = vec4f(clr.xyz * (1.0 + 0.6 * glow), clr.w);
                clr = vec4f(clr.xyz, mix(clr.w, 1.0, glow));
            } else {
                clr = vec4f(clr.xyz, clr.w * 0.12);
            }
        } else if (uniform.uEffectMode == 2) {
            // drift outro: warm sparks, brightness/alpha fade with the burst
            let delay: f32 = r3 * 0.15;
            let burstT: f32 = clamp((uniform.uEffectTime - delay) / max(0.2, 1.0 - delay), 0.0, 1.0);
            let life: f32 = 1.0 - burstT;
            clr = vec4f(mix(clr.xyz, uniform.uEffectColor, 0.5 * burstT), clr.w);
            clr = vec4f(clr.xyz * (1.0 + 0.8 * life * burstT), clr.w);
            clr = vec4f(clr.xyz, clr.w * (0.2 + 0.8 * life * life));
        }

        // apply saturation
        clr = vec4f(applySaturationToColor(clr.xyz), clr.w);

        // don't allow out-of-range alpha
        clr = vec4f(clr.xyz, clamp(clr.w, 0.0, 1.0));

        // apply tonemapping
        clr = vec4f(prepareOutputFromGamma(max(clr.xyz, vec3f(0.0)), -center.view.z), clr.w);

        // apply locked/selected colours
        if ((vertexState & 2u) != 0u) {
            clr = clr * uniform.lockedClr;
        } else if ((vertexState & 1u) != 0u) {
            clr = vec4f(mix(clr.xyz, uniform.selectedClr.xyz, uniform.selectedClr.a), clr.w);
        }

        output.color = clr;
    #endif

    return output;
}
`;

// Fragment stage: mirrors `fragmentShader` in splat-shader.ts. The forward path must
// write BOTH `output.color` (scene colour) and `output.color1` (selection overlay
// consumed by the outline/underlay passes) 閳?the two-attachment splat target needs a
// fragment output for every colour attachment.
const fragmentShaderWGSL = /* wgsl */`
varying texCoord_flags: vec4f;
varying color: vec4f;
varying vDeleted: f32;
uniform viewport_size: vec4f;

uniform outlineMode: i32;
uniform ringSize: f32;
uniform highlights: f32;
uniform shadows: f32;
uniform contrast: f32;

// HSL per-channel uniforms (8 zones packed into 2 vec4s each)
// A = [R, O, Y, G], B = [A, B, P, M]
uniform hslHueA: vec4f;
uniform hslHueB: vec4f;
uniform hslSatA: vec4f;
uniform hslSatB: vec4f;
uniform hslLumA: vec4f;
uniform hslLumB: vec4f;

// overall effect opacity (intro fade in / outro fade out)
#ifndef PICK_PASS
    uniform uEffectFade: f32;
#endif

// 运动期"不依赖顺序"的渲染（见 src/core/motion-opaque.ts）：
//   uMotionOpaque 0/1 开关；uMotionAlphaClip 是该路径下的 alpha 下限。
// 打开时：alpha 低于下限的片元直接丢弃、其余按**不透明**写出（颜色不预乘、alpha 写 1），
// 可见性完全交给深度测试（材质同时切到 BLEND_NONE + depthWrite）⇒ 与排序顺序无关。
uniform uMotionOpaque: f32;
uniform uMotionAlphaClip: f32;

// oriented crop-box clipping (same declarations as the vertex stage)
uniform uCropBoxEnabled: f32;
uniform uCropBoxPreview: f32;
uniform uCropBoxSoftEdge: f32;
uniform uViewToBoxLocal: mat4x4f;
// clip shape: 0 = box, 1 = cylinder (local Y axis), 2 = sphere/ellipsoid
uniform uCropBoxShape: f32;
uniform uCropBoxRadiusX: f32;
uniform uCropBoxRadiusY: f32;
uniform uCropBoxRadiusZ: f32;
uniform uCropBoxHeight: f32;
// cap plane: fragments just outside the shape form a solid section instead of
// vanishing. capWidth is in box-local units (0.5 = half box), capAlpha scales the
// section's opacity. The section keeps the splat's own colour (no repaint).
uniform uCropBoxCapWidth: f32;
uniform uCropBoxCapAlpha: f32;
uniform uCropBoxCapColor: vec4f;
varying vViewCenter: vec3f;
varying vScreenOffset: vec2f;
varying vDepthRadius: f32;
varying vEllipE00: f32;
varying vEllipE01: f32;
varying vEllipE02: f32;
varying vEllipE11: f32;
varying vEllipE12: f32;
varying vEllipE22: f32;

#if PICK_PASS
    uniform pickMode: i32;                  // 0: id, 1: depth estimation
#endif

const EXP4: f32 = 0.01831563888873418;      // exp(-4.0)
const INV_EXP4: f32 = 1.0 / (1.0 - EXP4);

fn normExp(x: f32) -> f32 {
    return (exp(x * -4.0) - EXP4) * INV_EXP4;
}

fn applyHighlights(c: vec3f) -> vec3f {
    let lum: f32 = dot(c, vec3f(0.299, 0.587, 0.114));
    let mask: f32 = smoothstep(0.4, 0.8, lum);
    return c + c * mask * uniform.highlights * 0.5;
}

fn applyShadows(c: vec3f) -> vec3f {
    let lum: f32 = dot(c, vec3f(0.299, 0.587, 0.114));
    let mask: f32 = 1.0 - smoothstep(0.2, 0.5, lum);
    return c + c * mask * uniform.shadows * 0.5;
}

fn applyContrast(c: vec3f) -> vec3f {
    return (c - vec3f(0.5)) * (1.0 + uniform.contrast) + vec3f(0.5);
}

// ---- Per-channel HSL (Lightroom-style) ----

// zone centres in [0,1] hue space (degrees / 360)
const ZC_RED: f32     = 0.0;
const ZC_ORANGE: f32  = 30.0 / 360.0;
const ZC_YELLOW: f32  = 60.0 / 360.0;
const ZC_GREEN: f32   = 120.0 / 360.0;
const ZC_AQUA: f32    = 180.0 / 360.0;
const ZC_BLUE: f32    = 225.0 / 360.0;
const ZC_PURPLE: f32  = 270.0 / 360.0;
const ZC_MAGENTA: f32 = 315.0 / 360.0;

fn hueDistance(h1: f32, h2: f32) -> f32 {
    let d: f32 = abs(h1 - h2);
    return min(d, 1.0 - d);
}

fn zoneWeight(hue: f32, center: f32) -> f32 {
    let d: f32 = hueDistance(hue, center);
    return 1.0 - smoothstep(15.0 / 360.0, 45.0 / 360.0, d);
}

fn rgb2hsl(c: vec3f) -> vec3f {
    let maxC: f32 = max(c.r, max(c.g, c.b));
    let minC: f32 = min(c.r, min(c.g, c.b));
    let l: f32 = (maxC + minC) * 0.5;
    let d: f32 = maxC - minC;
    var h: f32 = 0.0;
    var s: f32 = 0.0;
    if (d > 0.0001) {
        if (maxC == c.r) {
            h = (c.g - c.b) / d % 6.0;
            if (h < 0.0) { h = h + 6.0; }
            h = h / 6.0;
        } else if (maxC == c.g) {
            h = ((c.b - c.r) / d + 2.0) / 6.0;
        } else {
            h = ((c.r - c.g) / d + 4.0) / 6.0;
        }
        s = d / (1.0 - abs(2.0 * l - 1.0) + 0.0001);
    }
    return vec3f(h, s, l);
}

fn hue2rgb(p: f32, q: f32, tIn: f32) -> f32 {
    var t: f32 = tIn;
    if (t < 0.0) { t = t + 1.0; }
    if (t > 1.0) { t = t - 1.0; }
    if (t < 1.0 / 6.0) { return p + (q - p) * 6.0 * t; }
    if (t < 0.5) { return q; }
    if (t < 2.0 / 3.0) { return p + (q - p) * (2.0 / 3.0 - t) * 6.0; }
    return p;
}

fn hsl2rgb(h: f32, s: f32, l: f32) -> vec3f {
    if (s < 0.0001) { return vec3f(l); }
    let q: f32 = select(l + s - l * s, l * (1.0 + s), l < 0.5);
    let p: f32 = 2.0 * l - q;
    return vec3f(
        hue2rgb(p, q, h + 1.0 / 3.0),
        hue2rgb(p, q, h),
        hue2rgb(p, q, h - 1.0 / 3.0)
    );
}

fn applyPerChannelHSL(cIn: vec3f) -> vec3f {
    // early-out: skip if all adjustments are zero
    let sum: vec4f = uniform.hslHueA + uniform.hslHueB + uniform.hslSatA + uniform.hslSatB + uniform.hslLumA + uniform.hslLumB;
    if (dot(sum, sum) < 0.0001) { return cIn; }

    let c: vec3f = clamp(cIn, vec3f(0.0), vec3f(1.0));
    let hsl: vec3f = rgb2hsl(c);
    var h: f32 = hsl.x;
    var s: f32 = hsl.y;
    var l: f32 = hsl.z;

    // unrolled 8 zones
    let w0: f32 = zoneWeight(h, ZC_RED);
    let w1: f32 = zoneWeight(h, ZC_ORANGE);
    let w2: f32 = zoneWeight(h, ZC_YELLOW);
    let w3: f32 = zoneWeight(h, ZC_GREEN);
    let w4: f32 = zoneWeight(h, ZC_AQUA);
    let w5: f32 = zoneWeight(h, ZC_BLUE);
    let w6: f32 = zoneWeight(h, ZC_PURPLE);
    let w7: f32 = zoneWeight(h, ZC_MAGENTA);

    let totalW: f32 = w0 + w1 + w2 + w3 + w4 + w5 + w6 + w7;
    let totalHue: f32 =
        w0 * uniform.hslHueA.x + w1 * uniform.hslHueA.y + w2 * uniform.hslHueA.z + w3 * uniform.hslHueA.w +
        w4 * uniform.hslHueB.x + w5 * uniform.hslHueB.y + w6 * uniform.hslHueB.z + w7 * uniform.hslHueB.w;
    let totalSat: f32 =
        w0 * uniform.hslSatA.x + w1 * uniform.hslSatA.y + w2 * uniform.hslSatA.z + w3 * uniform.hslSatA.w +
        w4 * uniform.hslSatB.x + w5 * uniform.hslSatB.y + w6 * uniform.hslSatB.z + w7 * uniform.hslSatB.w;
    let totalLum: f32 =
        w0 * uniform.hslLumA.x + w1 * uniform.hslLumA.y + w2 * uniform.hslLumA.z + w3 * uniform.hslLumA.w +
        w4 * uniform.hslLumB.x + w5 * uniform.hslLumB.y + w6 * uniform.hslLumB.z + w7 * uniform.hslLumB.w;

    if (totalW > 0.0001) {
        // fract (not %) so a negative hue shift wraps into [0,1) like GLSL's mod
        h = fract(h + totalHue / totalW * 0.5);
        s = clamp(s + totalSat / totalW, 0.0, 1.0);
        l = clamp(l + totalLum / totalW * 0.5, 0.0, 1.0);
    }

    return hsl2rgb(h, s, l);
}

@fragment
fn fragmentMain(input: FragmentInput) -> FragmentOutput {
    var output: FragmentOutput;

    let A: f32 = dot(texCoord_flags.xy, texCoord_flags.xy);

    if (A > 1.0) {
        discard;
    }

    // crop-box per-fragment clipping
    var cropFade: f32 = 1.0;
    let finalColor: vec3f = color.xyz;
    if (uniform.uCropBoxEnabled > 0.5) {
        let dxy: vec2f = vScreenOffset - vViewCenter.xy;
        let A_coeff: f32 = vEllipE22;
        let B_coeff: f32 = 2.0 * (vEllipE02 * dxy.x + vEllipE12 * dxy.y);
        let C_coeff: f32 = vEllipE00 * dxy.x * dxy.x + vEllipE11 * dxy.y * dxy.y + 2.0 * vEllipE01 * dxy.x * dxy.y - 1.0;
        let disc: f32 = B_coeff * B_coeff - 4.0 * A_coeff * C_coeff;
        var depthOffset: f32;
        if (disc >= 0.0 && A_coeff > 1e-8) {
            depthOffset = (-B_coeff + sqrt(disc)) / (2.0 * A_coeff);
        } else {
            let cuv: vec2f = texCoord_flags.xy;
            let r2: f32 = dot(cuv, cuv);
            depthOffset = sqrt(max(0.0, 1.0 - r2)) * vDepthRadius;
        }
        let viewPos: vec3f = vec3f(vScreenOffset, vViewCenter.z + depthOffset);
        let localPos: vec3f = (uniform.uViewToBoxLocal * vec4f(viewPos, 1.0)).xyz;

        // distance to the clip-shape boundary (>0 inside, <0 outside). box / cylinder
        // (local Y axis, optional elliptic section) / ellipsoid share this test.
        var dist: f32;
        if (uniform.uCropBoxShape > 1.5) {
            // triaxial ellipsoid: radii (rx, ry, rz)
            let rx: f32 = max(uniform.uCropBoxRadiusX, 1e-4);
            let ry: f32 = max(uniform.uCropBoxRadiusY, 1e-4);
            let rz: f32 = max(uniform.uCropBoxRadiusZ, 1e-4);
            let q: vec3f = vec3f(localPos.x / rx, localPos.y / ry, localPos.z / rz);
            let s: f32 = length(q);
            dist = (1.0 - s) * min(min(rx, ry), rz);
        } else if (uniform.uCropBoxShape > 0.5) {
            // elliptic cylinder along local Y: (x/rx)^2 + (z/rz)^2 <= 1, |y| <= h/2
            let rx: f32 = max(uniform.uCropBoxRadiusX, 1e-4);
            let rz: f32 = max(uniform.uCropBoxRadiusZ, 1e-4);
            let q: vec2f = vec2f(localPos.x / rx, localPos.z / rz);
            let s: f32 = length(q);
            dist = min((1.0 - s) * min(rx, rz), uniform.uCropBoxHeight * 0.5 - abs(localPos.y));
        } else {
            // box
            let ad: vec3f = abs(localPos);
            let maxD: f32 = max(max(ad.x, ad.y), ad.z);
            dist = 0.5 - maxD;
        }

        if (dist < 0.0) {
            #if PICK_PASS
                discard;
            #else
                if (uniform.uCropBoxPreview > 0.5) {
                    cropFade = 0.035;
                } else {
                    // cap plane: fragments just outside the shape form the section and
                    // keep the splat's own colour (no repaint)
                    let capW: f32 = max(uniform.uCropBoxCapWidth, 0.0);
                    if (capW > 0.0 && dist > -capW) {
                        cropFade = smoothstep(-capW, 0.0, dist) * uniform.uCropBoxCapAlpha;
                    } else {
                        discard;
                    }
                }
            #endif
        } else {
            let softEdge: f32 = max(uniform.uCropBoxSoftEdge, 0.0005);
            cropFade = smoothstep(0.0, softEdge, dist);
        }
    }

    #if PICK_PASS
        if (uniform.pickMode == 1) {
            // depth estimation: premultiplied by alpha, blended additively
            let alpha: f32 = normExp(A);
            if (alpha < 1.0 / 255.0) {
                discard;
            }
            output.color = color * alpha;
        } else {
            // pick id
            output.color = color;
        }
    #else
        let norm: f32 = normExp(A);
        var alpha: f32 = norm * color.a;

        var graded: vec3f = applyHighlights(finalColor);
        graded = applyShadows(graded);
        graded = applyContrast(graded);
        graded = applyPerChannelHSL(graded);

        // deleted-but-shown splats are tinted red with reduced opacity
        if (vDeleted > 0.5) {
            graded = mix(graded, vec3f(1.0, 0.25, 0.25), 0.6);
            alpha = alpha * 0.4;
        }

        // apply crop-box fade
        alpha = alpha * cropFade;

        // overall effect opacity (intro fade in / outro fade out)
        alpha = alpha * uniform.uEffectFade;

        if (texCoord_flags.w == 0.0 && uniform.ringSize > 0.0) {
            // rings mode
            if (A < 1.0 - uniform.ringSize) {
                alpha = max(0.05, alpha);
            } else {
                alpha = 0.6;
            }
        }

        let selected: bool = texCoord_flags.z != 0.0 && texCoord_flags.w == 0.0;

        // RT0 = scene colour, RT1 = selection overlay (consumed by the outline and
        // underlay passes; the engine declares no colour1 for a single-output shader,
        // so assigning it here is what makes the two-attachment pass valid).
        if (uniform.outlineMode != 0) {
            output.color = vec4f(graded * alpha, alpha);
            output.color1 = vec4f(0.0, 0.0, 0.0, select(0.0, norm, selected));
        } else if (selected) {
            output.color = vec4f(graded * alpha * 0.8, alpha);
            output.color1 = vec4f(graded * alpha * 0.2, alpha);
        } else {
            output.color = vec4f(graded * alpha, alpha);
            output.color1 = vec4f(0.0, 0.0, 0.0, 0.0);
        }

        // 运动期的不透明路径：低 alpha 直接丢弃，其余不预乘、alpha 写 1（color1 与上面一致，
        // 选区/描边那条通路的行为不变）。可见性由深度测试决定 ⇒ 与排序顺序无关。
        if (uniform.uMotionOpaque > 0.5) {
            if (alpha < uniform.uMotionAlphaClip) {
                discard;
            }
            output.color = vec4f(graded, 1.0);
        }
    #endif

    return output;
}
`;

// `initCenter` with the per-splat transform palette applied to the model matrix,
// mirroring `gsplatCenter` in splat-shader.ts.
const gsplatCenterWGSL = /* wgsl */`
var splatTransform: texture_2d<u32>;            // per-splat index into the transform palette
var transformPalette: texture_2d<f32>;          // palette of transform matrices

fn applyPaletteTransform(model: mat4x4f) -> mat4x4f {
    let transformIndex: u32 = textureLoad(splatTransform, splat.uv, 0).r;
    if (transformIndex == 0u) {
        return model;
    }

    // read transform matrix (3 texels per matrix, 512 matrices per row)
    let u: i32 = i32(transformIndex % 512u) * 3;
    let v: i32 = i32(transformIndex / 512u);

    var t: mat4x4f;
    t[0] = textureLoad(transformPalette, vec2i(u, v), 0);
    t[1] = textureLoad(transformPalette, vec2i(u + 1, v), 0);
    t[2] = textureLoad(transformPalette, vec2i(u + 2, v), 0);
    t[3] = vec4f(0.0, 0.0, 0.0, 1.0);

    return model * transpose(t);
}

uniform matrix_model: mat4x4f;
// Camera matrices are fed as material parameters from splat.ts: on WebGPU the
// engine's own view uniform buffer is not correctly bound for this material in the
// app's custom render-pass pipeline (matrix_view reads as the identity matrix, so
// every splat projects to a degenerate point and the model never rasterizes).
// Matrix material parameters live in the material-generated uniform buffer, which
// this app does control, and are updated once per frame.
uniform uSplatView: mat4x4f;
uniform uSplatViewProj: mat4x4f;
uniform uSplatProj: mat4x4f;              // projection only (crop reconstruction)
uniform uSplatCameraParams: vec4f;        // 1 / far, far, near, isOrtho
uniform uSplatViewport: vec4f;            // width, height, 1 / width, 1 / height

// project the model space gaussian center to view and clip space
fn initCenter(modelCenter: vec3f, center: ptr<function, SplatCenter>) -> bool {
    let modelView: mat4x4f = uniform.uSplatView * applyPaletteTransform(uniform.matrix_model);
    let centerView: vec4f = modelView * vec4f(modelCenter, 1.0);

    #ifndef GSPLAT_CENTER_NOPROJ

        // early out if splat is behind the camera (perspective only);
        // orthographic projections are handled by frustum culling
        if (uniform.uSplatCameraParams.w != 1.0 && centerView.z > 0.0) {
            return false;
        }

        var centerProj: vec4f = uniform.uSplatViewProj * applyPaletteTransform(uniform.matrix_model) * vec4f(modelCenter, 1.0);

        // ensure gaussians are not clipped by the camera near and far planes
        centerProj.z = clamp(centerProj.z, 0.0, abs(centerProj.w));

        center.proj = centerProj;
        center.projMat00 = uniform.uSplatProj[0][0];

    #endif

    center.view = centerView.xyz / centerView.w;
    center.modelView = modelView;
    return true;
}
`;

// `modifySplat*` hooks: only the rotation/scale hook does work here (particle size
// per effect mode). Position and colour are handled in the main shader chunks.
const gsplatModifyWGSL = /* wgsl */`
    #ifndef PICK_PASS
        uniform uEffectMode: i32;
        uniform uEffectTime: f32;
        uniform uScatterRadius: f32;
        uniform uScatterCenter: vec3f;
    #endif

    fn modifySplatCenter(center: ptr<function, vec3f>) {
        // position transform happens in the SplatRoom main shader
    }

    fn modifySplatRotationScale(originalCenter: vec3f, modifiedCenter: vec3f, rotation: ptr<function, vec4f>, scale: ptr<function, vec3f>) {
        #ifndef PICK_PASS
            if (uniform.uEffectMode == 2) {
                // drift outro: sparks shrink as the burst progresses
                let seed: f32 = f32(splat.uv.x) * 0.61803398875 + f32(splat.uv.y) * 0.38196601125;
                let r3: f32 = fract(sin(seed * 33.912) * 7951.192);
                let delay: f32 = r3 * 0.15;
                let burstT: f32 = clamp((uniform.uEffectTime - delay) / max(0.45, 1.0 - delay), 0.0, 1.0);
                *scale = *scale * mix(1.0, 0.2, burstT);
            } else if (uniform.uEffectMode == 1) {
                // ripple intro: slightly larger particles on the wave front (glow)
                let waveRadius: f32 = uniform.uEffectTime * uniform.uScatterRadius * 1.6;
                let waveWidth: f32 = uniform.uScatterRadius * 0.12;
                let d: f32 = length(originalCenter - uniform.uScatterCenter);
                if (d >= waveRadius && d < waveRadius + waveWidth) {
                    let bandT: f32 = (d - waveRadius) / max(waveWidth, 1e-5);
                    let glow: f32 = 1.0 - bandT;
                    *scale = *scale * (1.0 + 1.3 * glow);
                }
            }
        #endif
    }

    fn modifySplatColor(center: vec3f, color: ptr<function, vec4f>) {
        // colour transform happens in the SplatRoom main shader
    }
`;

// Copy of the engine's `gsplatCornerVS` chunk (covariance projection) whose only
// difference is that the viewport size comes from a material parameter instead of
// the engine view uniform buffer (see the notes in gsplatCenterWGSL).
const gsplatCornerWGSL = /* wgsl */`
uniform uSplatViewport: vec4f;             // viewport width, height, 1 / width, 1 / height
uniform minPixelSize: f32;

// rotation and scale source data are f16; covariance must be f32 to avoid scale^2 overflow
fn computeCovariance(rotation: half4, scale: half3, covA_ptr: ptr<function, vec3f>, covB_ptr: ptr<function, vec3f>) {
    let rot: half3x3 = quatToMat3(rotation);
    let s: vec3f = vec3f(scale);

    // M = S * R (promote to f32 to avoid overflow in dot products)
    let M: mat3x3f = transpose(mat3x3f(
        s.x * vec3f(rot[0]),
        s.y * vec3f(rot[1]),
        s.z * vec3f(rot[2])
    ));

    *covA_ptr = vec3f(dot(M[0], M[0]), dot(M[0], M[1]), dot(M[0], M[2]));
    *covB_ptr = vec3f(dot(M[1], M[1]), dot(M[1], M[2]), dot(M[2], M[2]));
}

// calculate the clip-space offset from the center for this gaussian
fn initCornerCov(source: ptr<function, SplatSource>, center: ptr<function, SplatCenter>, corner: ptr<function, SplatCorner>, covA: vec3f, covB: vec3f) -> bool {
    let Vrk = mat3x3f(
        vec3f(covA.x, covA.y, covA.z),
        vec3f(covA.y, covB.x, covB.y),
        vec3f(covA.z, covB.y, covB.z)
    );

    let focal = uniform.uSplatViewport.x * center.projMat00;
    let v = center.view.xyz;

    // standard perspective Jacobian
    let vp = select(center.view.xyz, vec3f(0.0, 0.0, 1.0), uniform.uSplatCameraParams.w == 1.0);
    let J1 = focal / vp.z;
    let J2 = -J1 / vp.z * vp.xy;
    let J = mat3x3f(
        vec3f(J1, 0.0, J2.x),
        vec3f(0.0, J1, J2.y),
        vec3f(0.0, 0.0, 0.0)
    );

    let W = transpose(mat3x3f(center.modelView[0].xyz, center.modelView[1].xyz, center.modelView[2].xyz));
    let T = W * J;
    let cov = transpose(T) * Vrk * T;

    #if GSPLAT_AA
        let detOrig = cov[0][0] * cov[1][1] - cov[0][1] * cov[1][0];
        let detBlur = (cov[0][0] + 0.3) * (cov[1][1] + 0.3) - cov[0][1] * cov[1][0];
        corner.aaFactor = half(sqrt(max(detOrig / detBlur, 0.0)));
    #endif

    let diagonal1 = cov[0][0] + 0.3;
    let offDiagonal = cov[0][1];
    let diagonal2 = cov[1][1] + 0.3;

    let mid = 0.5 * (diagonal1 + diagonal2);
    let radius = length(vec2f((diagonal1 - diagonal2) / 2.0, offDiagonal));
    let lambda1 = mid + radius;
    let lambda2 = max(mid - radius, 0.1);

    // use the smaller viewport dimension to limit the kernel size against the screen resolution
    let vmin = min(1024.0, min(uniform.uSplatViewport.x, uniform.uSplatViewport.y));

    let l1 = 2.0 * min(sqrt(2.0 * lambda1), vmin);
    let l2 = 2.0 * min(sqrt(2.0 * lambda2), vmin);

    // early-out gaussians smaller than minPixelSize
    if (max(l1, l2) < uniform.minPixelSize) {
        return false;
    }

    let c = center.proj.ww * uniform.uSplatViewport.zw;

    // cull against frustum x/y axes
    if (any((abs(center.proj.xy) - vec2f(max(l1, l2)) * c) > center.proj.ww)) {
        return false;
    }

    let diagonalVector = normalize(vec2f(offDiagonal, lambda1 - diagonal1));
    let v1 = l1 * diagonalVector;
    let v2 = l2 * vec2f(diagonalVector.y, -diagonalVector.x);

    corner.offset = vec3f((f32(source.cornerUV.x) * v1 + f32(source.cornerUV.y) * v2) * c, 0.0);
    corner.uv = source.cornerUV;

    return true;
}

// calculate the clip-space offset from the center for this gaussian
fn initCorner(source: ptr<function, SplatSource>, center: ptr<function, SplatCenter>, corner: ptr<function, SplatCorner>) -> bool {
    var rotation: vec4f = getRotation().yzwx;  // (w,x,y,z) to (x,y,z,w)
    var scale: vec3f = getScale();

    // hook: modify rotation and scale
    modifySplatRotationScale(center.modelCenterOriginal, center.modelCenterModified, &rotation, &scale);

    var covA: vec3f;
    var covB: vec3f;
    computeCovariance(half4(rotation.wxyz), half3(scale), &covA, &covB);

    return initCornerCov(source, center, corner, covA, covB);
}
`;

export { vertexShaderWGSL, fragmentShaderWGSL, gsplatCenterWGSL, gsplatModifyWGSL, gsplatCornerWGSL };
